### ISSUE TITLE
import error in data_handling.py

### ISSUE THREAD

**Issue by yanedge** [mad-lab-fau/sleep_analysis#2]
`from sleep_analysis.preprocessing.mesa_dataset.edr import extract_edr_features` fails because the import is looking into the `preprocessing/mesa_dataset/edr` directory instead of `preprocessing/mesa_dataset/edr.py` file

**Comment by danielkrauss2** [comment]
Should be fixed now! Thank you!

This happened because I moved the EDR extraction methods from another repository into this one
